### ISSUE TITLE
Opprette brukere til vegvesenet for å forberede flytting av redaksjonelle sider

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-cms-service#102]
Forslag til steg: 

- [x] Opprett brukere for Cathrine Ruud, Hilde Austlid og Mette Hendbukt i staging. 
- [x] Opprette egne collection types i strapi. Brukerne skal kun ha tilgang til å opprette og redigere sider for eget område, ikke for resten av portalløsningen. 
- [x] Teste at løsningen fungerer som forventet
- [ ] Gi tilsvarende tilgang i produksjon

**Comment by valosnah** [comment]
Testet at bruker i egen testrolle uten tilganger ikke har tilgang til våre ressurser.

**Comment by jeffreiffers** [comment]
Har vi noe informasjon om hvordan collection types skal se ut?

**Comment by jeffreiffers** [comment]
Opprettet egen rolle og brukere. Har også opprettet ny collection type TransportArticle.

**Comment by KjerstiSteien** [comment]
@jeffreiffers kan vi gi tilsvarende tilgang i produksjon nå og lukke saken, eller venter vi på noe?

**Comment by jeffreiffers** [comment]
Ja vi kan det. Skal forsøke å gjøre det i dag.
