### ISSUE TITLE
Legg BACKEND_SERVICE_ID og PROJECT_NUMBER inn i konfigurasjonsseksjonen

### ISSUE THREAD

**Issue by simenandre** [Informasjonsforvaltning/fdk-cms-service#30]
_Dette er kun en forbedring_: Vi bør aldri referere `process.env` direkte, siden det fort blir uoversiktlig.

Vi bør rydde opp i referansene som ble lagt inn på #28

**Comment by KjerstiSteien** [comment]
@jeffreiffers anser du dette som relevant fortsatt?

**Comment by jeffreiffers** [comment]
Ser ikke noe behov for det.
