### ISSUE TITLE
Tilgangsstyring: vurder og implementer tilgangsstyring

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-cms-service#5]
Vi bør integrere mot eksisterande tilgangsstyringsmekanismer.

I dag brukar vi "Felles brukarhandtering", men antagelegvis bør vi nytte høvet til å vurdere om vi kan feks benytte ein anna provider.

Dette issuet tracker diskusjon og implementering av tilgangsstyring.

**Comment by cobraz** [comment]
Ser ut til at [det skal være greit å implementere OAuth](https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#providers). 

Vi kan [legge til en tilpasset provider](https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#adding-a-new-provider-to-your-project). Jeg kan gjerne sette i gang med dette, men trenger litt hjelp med å vite hva slags løsning og tilgang på det.

**Comment by cobraz** [comment]
Dette er i orden 👍

Må bare skrus på med enkle miljøvariabler :)
